name: Run test when push
on: pull_request
jobs:
  downloadRepostitroy:
    runs-on: ubuntu-latest
    steps:
      - name: if label is good to merge
        # if: github.event.label.name == good to merge
        run: echo '${{toJSON(github.event)}}'
      - name: download github repositroy
        uses: actions/checkout@v7
      - name: set up node servier
        uses: actions/setup-node@v7
      - name: install dependencies
        run: npm ci
      - name: Running test cases
        run: npm test