name: Run test when push
on: push
jobs:
  downloadRepostitroy:
    runs-on: ubuntu-latest
    steps:
      - name: download github repositroy
        uses: actions/checkout@v7
      - name: set up node servier
        uses: actions/setup-node@v7
      - name: install dependencies
        run: npm ci
      - name: check files
        run: |
          pwd -la

  runTest:
    runs-on: ubuntu-latest
    needs: downloadRepostitroy
    steps:
      - name: Running test cases
        working-directory: ./../
        run: npm test      